#!/usr/bin/env python

"""
CLI for interacting with the HNSearch API.
"""

from newsyc import cli


def main():
    parser = cli.create_parser()
    options = parser.parse_args()
    cli.search(options)


if __name__ == '__main__':
    main()
