#!/usr/bin/env python

"""
CLI for interacting with the HNSearch API.
"""

import sys
import simplejson as json

try:
    from pygments import highlight
    from pygments.formatters import TerminalFormatter
    from pygments.lexers import JavascriptLexer
    have_pygments = True
except ImportError:
    have_pygments = False


def print_formatted_json(stream, json_data, indentation):
    """Format and print JSON."""
    formatted = json.dumps(json_data, indent=indentation)
    if have_pygments and getattr(stream, 'isatty', lambda: False)():
        formatter, lexer = TerminalFormatter(), JavascriptLexer()
        formatted = highlight(formatted, formatter=formatter, lexer=lexer)
    print >> stream, formatted.rstrip()


def decorate(stream, indent=2):
    """Turn JSON into something readable."""
    json_data = json.load(stream)
    print_formatted_json(sys.stdout, json_data, indent)
    sys.stdout.write('\n')
